name: Build luci-app-fancontrol with SDK

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      
    - name: Install minimal dependencies
      run: |
        sudo apt-get update
        sudo apt install -y \
          build-essential \
          ccache \
          curl \
          gawk \
          git \
          libncurses5-dev \
          libssl-dev \
          make \
          python3 \
          rsync \
          unzip \
          wget
        sudo apt clean
        
    - name: Download OpenWrt SDK
      run: |
        SDK_URL="http://downloads.openwrt.org/releases/23.05.6/targets/rockchip/armv8/openwrt-sdk-23.05.6-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
        wget $SDK_URL
        tar xf openwrt-sdk-*.tar.xz
        rm openwrt-sdk-23.05.6-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        cd openwrt-sdk-*
        echo "SDK_PATH=$PWD" >> $GITHUB_ENV
        
    - name: Add fancontrol package to SDK
      run: |
        cd $SDK_PATH
        # 将当前仓库的代码复制到SDK中
        git clone https://github.com/LeeHe-gif/luci-app-fancontrol.git package/fancontrol
        
    - name: Build the package
      run: |
        cd $SDK_PATH
        # 创建一个基本的.config文件，避免menuconfig
        cat > .config << 'EOF'
        CONFIG_TARGET_rockchip_armv8=y
        # 设置一些基本配置
        CONFIG_ALL=y
        CONFIG_ALL_KMODS=y
        CONFIG_ALL_NONSHARED=y
        # 禁用一些不必要的特性以加速编译
        CONFIG_DEVEL=n
        CONFIG_CCACHE=n
        CONFIG_SIGNED_PACKAGES=n
        EOF
    
        # 应用配置
        make defconfig
            
        # 现在编译包
        make package/fancontrol/compile V=s
        
    - name: Collect IPK files
      run: |
        cd $SDK_PATH
        mkdir -p ../artifacts
        find bin -name "*fancontrol*.ipk" -exec cp {} ../artifacts/ \;
        echo "Generated IPK files:"
        ls -la ../artifacts/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fancontrol-ipk
        path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ipk-packages
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          OpenWrt 23.05.06 插件包 (rockchip  armv8 架构)
          包含:
          - luci-app-fancontrol 主程序
          - 中文语言包 (如存在)
        files: |
          *.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
